import type { AgentDefinition } from '../shared/types';

/**
 * Registry of every AI agent supported by Headroom (see `headroom wrap --help`,
 * headroom v0.32.x). Each entry describes how to detect the agent on Windows,
 * macOS and Linux, which proxy environment variables it understands and which
 * port the launcher suggests by default (unique per agent so several agents
 * can run through their own proxies concurrently).
 */
export const AGENTS: AgentDefinition[] = [
  {
    id: 'claude',
    name: 'Claude Code',
    vendor: 'Anthropic',
    description: 'Anthropic\u2019s agentic coding CLI. Routed through Headroom via ANTHROPIC_BASE_URL.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['claude'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\claude.cmd', '~\\.claude\\local\\claude.exe'],
      darwin: ['~/.claude/local/claude', '/usr/local/bin/claude', '/opt/homebrew/bin/claude'],
      linux: ['~/.claude/local/claude', '/usr/local/bin/claude', '~/.local/bin/claude'],
    },
    envStyle: 'anthropic',
    defaultArgs: [],
    configFileHint: '~/.claude/settings.json',
    defaultPort: 8798,
    accent: '#d97706',
    homepage: 'https://claude.ai/code',
  },
  {
    id: 'codex',
    name: 'OpenAI Codex CLI',
    vendor: 'OpenAI',
    description: 'OpenAI\u2019s coding agent CLI. Routed through Headroom via OPENAI_BASE_URL.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['codex'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\codex.cmd'],
      darwin: ['/usr/local/bin/codex', '/opt/homebrew/bin/codex'],
      linux: ['/usr/local/bin/codex', '~/.local/bin/codex'],
    },
    envStyle: 'openai',
    defaultArgs: [],
    configFileHint: '~/.codex/config.toml',
    defaultPort: 8989,
    accent: '#10a37f',
    homepage: 'https://github.com/openai/codex',
  },
  {
    id: 'cline',
    name: 'Cline',
    vendor: 'Cline',
    description: 'Autonomous coding agent, available as a VS Code extension and a Node CLI.',
    interfaceType: 'ide-extension',
    launchStrategy: 'env',
    executables: ['cline'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\cline.cmd'],
      darwin: ['/usr/local/bin/cline', '/opt/homebrew/bin/cline'],
      linux: ['/usr/local/bin/cline', '~/.local/bin/cline'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: 'VS Code settings \u2192 Cline \u2192 API Provider (OpenAI/Anthropic compatible, base URL http://127.0.0.1:<port>)',
    defaultPort: 8790,
    accent: '#8b5cf6',
    homepage: 'https://cline.bot',
  },
  {
    id: 'continue',
    name: 'Continue',
    vendor: 'Continue',
    description: 'Open-source AI code assistant for VS Code and JetBrains. Headroom injects its systemMessage.',
    interfaceType: 'ide-extension',
    launchStrategy: 'instructions',
    executables: ['continue', 'cn'],
    wellKnownPaths: {},
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.continue/config.json (or config.yaml)',
    defaultPort: 8796,
    accent: '#7c3aed',
    homepage: 'https://continue.dev',
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot CLI',
    vendor: 'GitHub',
    description: 'GitHub Copilot agentic CLI. Supports model selection, e.g. --model claude-sonnet-4.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['copilot'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\copilot.cmd'],
      darwin: ['/usr/local/bin/copilot', '/opt/homebrew/bin/copilot'],
      linux: ['/usr/local/bin/copilot', '~/.local/bin/copilot'],
    },
    envStyle: 'openai',
    defaultArgs: [],
    configFileHint: '~/.copilot/config.json',
    defaultPort: 8794,
    accent: '#6e40c9',
    homepage: 'https://github.com/features/copilot',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vendor: 'Anysphere',
    description: 'AI-first code editor (desktop app). Launch with proxy env or point its model settings at the proxy.',
    interfaceType: 'gui',
    launchStrategy: 'env',
    executables: ['cursor', 'Cursor'],
    wellKnownPaths: {
      win32: ['%LOCALAPPDATA%\\Programs\\cursor\\Cursor.exe'],
      darwin: ['/Applications/Cursor.app/Contents/MacOS/Cursor'],
      linux: ['/usr/bin/cursor', '/usr/local/bin/cursor', '~/Applications/cursor.AppImage'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: 'Cursor Settings \u2192 Models \u2192 OpenAI/Anthropic base URL',
    defaultPort: 8795,
    accent: '#0ea5e9',
    homepage: 'https://cursor.com',
  },
  {
    id: 'goose',
    name: 'Goose',
    vendor: 'Block',
    description: 'Block\u2019s open-source AI agent CLI for engineering tasks.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['goose'],
    wellKnownPaths: {
      win32: ['~\\.local\\bin\\goose.exe'],
      darwin: ['~/.local/bin/goose', '/opt/homebrew/bin/goose'],
      linux: ['~/.local/bin/goose', '/usr/local/bin/goose'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.config/goose/config.yaml',
    defaultPort: 8797,
    accent: '#f59e0b',
    homepage: 'https://block.github.io/goose',
  },
  {
    id: 'grok',
    name: 'Grok CLI',
    vendor: 'xAI',
    description: 'xAI\u2019s Grok coding CLI. Installs under ~/.grok/bin.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['grok'],
    wellKnownPaths: {
      win32: ['~\\.grok\\bin\\grok.exe'],
      darwin: ['~/.grok/bin/grok'],
      linux: ['~/.grok/bin/grok'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.grok/config.toml',
    defaultPort: 8791,
    accent: '#e11d48',
    homepage: 'https://x.ai',
  },
  {
    id: 'grok-build',
    name: 'Grok Build',
    vendor: 'xAI',
    description: 'Grok Build mode \u2014 reads ~/.grok/config.toml; Headroom updates it to point at the proxy.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['grok'],
    wellKnownPaths: {
      win32: ['~\\.grok\\bin\\grok.exe'],
      darwin: ['~/.grok/bin/grok'],
      linux: ['~/.grok/bin/grok'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.grok/config.toml',
    defaultPort: 8792,
    accent: '#fb7185',
    homepage: 'https://x.ai',
  },
  {
    id: 'kimi',
    name: 'Kimi CLI',
    vendor: 'Moonshot AI',
    description: 'Moonshot AI\u2019s Kimi coding CLI (Anthropic-compatible API).',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['kimi'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\kimi.cmd'],
      darwin: ['/usr/local/bin/kimi', '/opt/homebrew/bin/kimi'],
      linux: ['/usr/local/bin/kimi', '~/.local/bin/kimi'],
    },
    envStyle: 'anthropic',
    defaultArgs: [],
    configFileHint: '~/.kimi/config.json',
    defaultPort: 8799,
    accent: '#2563eb',
    homepage: 'https://www.moonshot.ai',
  },
  {
    id: 'omp',
    name: 'Oh My Pi',
    vendor: 'Oh My Pi',
    description: 'Oh My Pi (omp) coding agent CLI.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['omp'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\omp.cmd'],
      darwin: ['/usr/local/bin/omp', '/opt/homebrew/bin/omp'],
      linux: ['/usr/local/bin/omp', '~/.local/bin/omp'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.omp/config.json',
    defaultPort: 8800,
    accent: '#14b8a6',
    homepage: 'https://ohmy.pi',
  },
  {
    id: 'openclaude',
    name: 'OpenClaude',
    vendor: 'OpenClaude',
    description: 'Open-source Claude-compatible coding CLI.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['openclaude'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\openclaude.cmd'],
      darwin: ['/usr/local/bin/openclaude', '/opt/homebrew/bin/openclaude'],
      linux: ['/usr/local/bin/openclaude', '~/.local/bin/openclaude'],
    },
    envStyle: 'anthropic',
    defaultArgs: [],
    configFileHint: '~/.openclaude/config.json',
    defaultPort: 8801,
    accent: '#f97316',
    homepage: 'https://github.com',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    vendor: 'OpenClaw',
    description: 'OpenClaw agent \u2014 Headroom bootstraps its plugin (distinct from OpenCode).',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['openclaw'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\openclaw.cmd'],
      darwin: ['/usr/local/bin/openclaw', '/opt/homebrew/bin/openclaw'],
      linux: ['/usr/local/bin/openclaw', '~/.local/bin/openclaw'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.openclaw/config.json',
    defaultPort: 8802,
    accent: '#84cc16',
    homepage: 'https://github.com',
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    vendor: 'SST',
    description: 'Terminal-first AI coding agent from SST.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['opencode'],
    wellKnownPaths: {
      win32: ['~\\.opencode\\bin\\opencode.exe', '%APPDATA%\\npm\\opencode.cmd'],
      darwin: ['~/.opencode/bin/opencode', '/opt/homebrew/bin/opencode'],
      linux: ['~/.opencode/bin/opencode', '~/.local/bin/opencode'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.config/opencode/opencode.json',
    defaultPort: 8803,
    accent: '#22d3ee',
    homepage: 'https://opencode.ai',
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    vendor: 'All Hands AI',
    description: 'Open-source AI software-engineering agent (formerly OpenDevin).',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['openhands'],
    wellKnownPaths: {
      win32: ['~\\AppData\\Roaming\\Python\\Scripts\\openhands.exe'],
      darwin: ['/usr/local/bin/openhands', '~/.local/bin/openhands'],
      linux: ['~/.local/bin/openhands', '/usr/local/bin/openhands'],
    },
    envStyle: 'openai',
    defaultArgs: [],
    configFileHint: '~/.openhands/config.toml',
    defaultPort: 8804,
    accent: '#a3e635',
    homepage: 'https://github.com/All-Hands-AI/OpenHands',
  },
  {
    id: 'vibe',
    name: 'Mistral Vibe',
    vendor: 'Mistral AI',
    description: 'Mistral AI\u2019s vibe-coding CLI.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['vibe'],
    wellKnownPaths: {
      win32: ['%APPDATA%\\npm\\vibe.cmd'],
      darwin: ['/usr/local/bin/vibe', '/opt/homebrew/bin/vibe'],
      linux: ['/usr/local/bin/vibe', '~/.local/bin/vibe'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.vibe/config.toml',
    defaultPort: 8805,
    accent: '#ff7000',
    homepage: 'https://mistral.ai',
  },
  {
    id: 'zcode',
    name: 'ZCode',
    vendor: 'Z.ai',
    description: 'ZCode desktop app (zcode.z.ai). Headroom configures it to talk to the local proxy.',
    interfaceType: 'gui',
    launchStrategy: 'env',
    executables: ['zcode', 'ZCode'],
    wellKnownPaths: {
      win32: ['%LOCALAPPDATA%\\Programs\\zcode\\ZCode.exe'],
      darwin: ['/Applications/ZCode.app/Contents/MacOS/ZCode'],
      linux: ['/usr/bin/zcode', '~/Applications/ZCode.AppImage'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: 'ZCode Settings \u2192 Provider base URL',
    defaultPort: 8806,
    accent: '#6366f1',
    homepage: 'https://zcode.z.ai',
  },
  {
    id: 'aider',
    name: 'Aider',
    vendor: 'Paul Gauthier',
    description: 'AI pair programming in your terminal, works with many providers.',
    interfaceType: 'cli',
    launchStrategy: 'env',
    executables: ['aider'],
    wellKnownPaths: {
      win32: ['~\\AppData\\Roaming\\Python\\Scripts\\aider.exe'],
      darwin: ['/usr/local/bin/aider', '/opt/homebrew/bin/aider', '~/.local/bin/aider'],
      linux: ['~/.local/bin/aider', '/usr/local/bin/aider'],
    },
    envStyle: 'both',
    defaultArgs: [],
    configFileHint: '~/.aider.conf.yml',
    defaultPort: 8793,
    accent: '#ec4899',
    homepage: 'https://aider.chat',
  },
];

const byId = new Map(AGENTS.map((a) => [a.id, a]));

/** Look up an agent definition by id. Throws on unknown id. */
export function getAgent(id: string): AgentDefinition {
  const found = byId.get(id);
  if (!found) {
    throw new Error(`Unknown agent id: ${id}`);
  }
  return found;
}

/** True when an agent id exists in the registry. */
export function hasAgent(id: string): boolean {
  return byId.has(id);
}
